#ifndef __ICATCH_PREVIEW_MODE_H__
#define __ICATCH_PREVIEW_MODE_H__

enum ICatchPreviewMode {
	ICATCH_STILL_PREVIEW_MODE				= 0x01,
	ICATCH_VIDEO_PREVIEW_MODE				= 0x02,
	ICATCH_TIMELAPSE_STILL_PREVIEW_MODE		= 0x03,
	ICATCH_TIMELAPSE_VIDEO_PREVIEW_MODE		= 0x04
};

#endif

