#ifndef __ICATCH_WIFI_CAM_LIGHT_FREQUENCY_H__
#define __ICATCH_WIFI_CAM_LIGHT_FREQUENCY_H__

enum ICatchLightFrequency {
	LIGHT_FREQUENCY_UNDEFINED	= 0xFF,
	LIGHT_FREQUENCY_50HZ		= 0x00,
	LIGHT_FREQUENCY_60HZ		= 0x01,
	LIGHT_FREQUENCY_AUTO		= 0x02,
	
};

#endif
