#ifndef __ICATCH_MODE_H__
#define __ICATCH_MODE_H__

enum ICatchMode {
	ICATCH_MODE_CAMERA		= 0x0001,
	ICATCH_MODE_VIDEO		= 0x0002,
	ICATCH_MODE_TIMELAPSE	= 0x0003,
	ICATCH_MODE_UNDEFINED	= 0xFFFF,
};

enum ICatchCameraWifiMode {
	ICATCH_CAMERA_WIFI_MODE_AP			= 0x0001,
	ICATCH_CAMERA_WIFI_MODE_STATION		= 0x0002,
	ICATCH_CAMERA_WIFI_MODE_ETHERNET	= 0x0003,
};
#endif
