#ifndef __ICATCH_PROP_DATA_TYPE_H__
#define __ICATCH_PROP_DATA_TYPE_H__

enum ICatchPropDataType {
	ICATCH_PROP_FORM_FLAG_ENUM	= 0x01,
	ICATCH_PROP_FORM_FLAG_RANGE	= 0x02,
	ICATCH_PROP_FORM_FLAG_NONE	= 0x03,
};

#endif
